const { BaseEngine, clean, formatDate, formatCurrency } = require('./baseEngine');

/**
 * ReportDocumentEngine — generic reports (fee collection, attendance, etc.).
 * Clean, minimal, professional. No heavy boxes or colored bars.
 */
class ReportDocumentEngine extends BaseEngine {
  async generateReport(school, data, options = {}) {
    const orientation = data.orientation || 'portrait';
    const margin = 40;
    const doc = this.createDoc({
      size: 'A4',
      orientation,
      margins: { top: margin, bottom: margin, left: margin, right: margin },
    });
    const bufferPromise = this.collectBuffer(doc);
    const contentWidth = doc.page.width - margin * 2;

    this.drawWatermark(doc, school);
    this.drawHeader(doc, school, { margin });

    // Title
    doc.y += 4;
    this.drawTitle(doc, data.title || 'Report', { margin });

    // Subtitle — subtle
    if (data.subtitle) {
      doc.fontSize(10).font('Helvetica').fillColor('#6b7280');
      doc.text(data.subtitle, margin, doc.y, { align: 'center', width: contentWidth });
      doc.y += 6;
    }

    // Filters — clean text, no box
    if (data.filters && Object.keys(data.filters).length) {
      doc.y += 4;
      doc.fontSize(8).font('Helvetica').fillColor('#9ca3af');
      const filterParts = Object.entries(data.filters)
        .filter(([_, v]) => v && v !== 'all' && v !== '')
        .map(([k, v]) => `${k}: ${v}`);
      if (filterParts.length) {
        doc.text(filterParts.join('  ·  '), margin, doc.y, { width: contentWidth });
        doc.y += 8;
      }
    }

    // Generated date — subtle, right-aligned
    doc.fontSize(8).font('Helvetica').fillColor('#9ca3af');
    doc.text(`Generated: ${formatDate(data.generatedDate || new Date())}`, margin, doc.y, { width: contentWidth, align: 'right' });
    doc.y += 8;

    // Data table
    if (data.columns && data.rows) {
      doc.y += 4;
      const colCount = data.columns.length;
      const colWidths = data.columnWidths || this._autoColumnWidths(colCount, contentWidth);

      const headers = data.columns.map(c => c.label || c.header || c);
      const aligns = data.columns.map(c => c.align || 'left');
      const rows = data.rows.map(row => {
        if (Array.isArray(row)) return row;
        return data.columns.map(c => row[c.key || c.field] ?? row[c.label] ?? '');
      });

      this.drawTable(doc, {
        headers, rows, widths: colWidths, x: margin, y: doc.y,
        aligns, repeatHeader: true,
        fontSize: 8, headerFontSize: 7, rowHeight: 16, headerHeight: 18,
      });
    }

    // Summary — clean text
    if (data.summary && Object.keys(data.summary).length) {
      doc.y += 8;
      doc.fontSize(9).font('Helvetica-Bold').fillColor('#1a1a1a');
      doc.text('Summary', margin, doc.y, { width: contentWidth });
      doc.y += 4;

      const summaryRows = Object.entries(data.summary).map(([key, value]) => [
        { text: key, bold: true },
        clean(value),
      ]);

      if (summaryRows.length) {
        const sumW = [contentWidth * 0.6, contentWidth * 0.4];
        this.drawTable(doc, {
          headers: ['Metric', 'Value'],
          rows: summaryRows,
          widths: sumW,
          x: margin, y: doc.y,
          aligns: ['left', 'right'],
          fontSize: 9, rowHeight: 16,
        });
      }
    }

    // Generated by — subtle
    if (data.generatedBy) {
      doc.y += 6;
      doc.fontSize(8).font('Helvetica').fillColor('#9ca3af');
      doc.text(`Generated by: ${data.generatedBy}`, margin, doc.y, { width: contentWidth });
    }

    this.drawFooter(doc, school, { margin });

    doc.end();
    return bufferPromise;
  }

  _autoColumnWidths(colCount, totalWidth) {
    const w = totalWidth / colCount;
    return Array(colCount).fill(w);
  }
}

module.exports = ReportDocumentEngine;
